micronaut:
  application:
    name: scotPowerTechTest
  server:
    port: 8082
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:h2:mem:readings_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
